Repository SCE-Development/Clark, pull requests merged in 2019-11, with the labels that each got.

#109 Fixed Unit Tests for MongoDB
  api/routes/3DPrintingForm.js
  test/3DPrintingForm.js
  test/user.js
Labels: API, Testing

#108 Thai/login
  src/Pages/Login/Login.css
  src/Pages/Login/Login.js
  src/Pages/MembershipApplication/membershipApplication.jsx
  src/Pages/TheTeam/App.css
Labels: Front End, enhancement

#112 Added Enzyme for React Component Testing
  .babelrc
  package.json
  src/App.js
  src/index.js
  test/App.test.js
Labels: Front End, Testing
