Repository SCE-Development/Clark, pull requests merged in 2020-11, with the labels that each got.

#697 more dependas
  package.json
Labels: dependencies

#606 Added Access Level Verification
  api/main_endpoints/routes/3DPrintingForm.js
  api/main_endpoints/routes/Auth.js
  api/main_endpoints/routes/DoorCode.js
  api/main_endpoints/routes/Event.js
  api/main_endpoints/routes/InventoryItem.js
  api/main_endpoints/routes/User.js
  api/main_endpoints/routes/officerManager.js
  api/main_endpoints/util/token-functions.js
  src/Pages/Login/Login.js
  src/Pages/Login/login.css
  test/TokenFunctions.js
  test/User.js
Labels: API

#700 Fixing callback url for email verification
  api/cloud_api/email_templates/verification.js
Labels: bug
