Repository SCE-Development/Clark, pull requests merged in 2020-03, with the labels that each got.

#334 Refactor 3DPrintForm Page
  src/Pages/3DPrinting/3D-print-form.css
  src/Pages/3DPrinting/3DPrintForm.js
Labels: Front End, Refactoring

#344 Fixed Strange Error
  package.json
Labels: bug

#337 Added ErrorLog API Function
  src/APIFunctions/ErrorLog.js
  test/ErrorLog.js
Labels: API, Front End, enhancement

#346 Write SignLog API
  api/index.js
  api/models/SignLog.js
  api/routes/SignLog.js
  src/APIFunctions/SignLog.js
  test/SignLog.js
Labels: API, enhancement

#348 Limit LED Sign Inputs
  src/Pages/LedSign/LedSign.js
  src/Pages/LedSign/led-sign.css
Labels: Front End, enhancement

#333 Integrate ConfimationModal into code
  src/Pages/2DPrinting/2DPrinting.js
  src/Pages/EventManager/EventManagerModal.js
  src/Pages/Overview/OverviewProfile.js
Labels: Front End, Refactoring, enhancement

#328 Fix table overflow bug
  src/APIFunctions/Profile.js
  src/Pages/Overview/Overview.css
  src/Pages/Overview/OverviewProfile.js
  src/Pages/Profile/MemberView/Profile.jsx
Labels: bug

#315 Change reset pages from button to checkbox
  src/Pages/Profile/admin/EditorForm.js
  src/Pages/Profile/admin/editor-form.css
  test/frontend/EditorForm.test.js
Labels: Front End, bug

#340 Make Backend an Independent Directory
  .gitignore
  api/mailer/auth.js
  api/models/User.js
  api/package-lock.json
  api/package.json
  api/routes/LedSign.js
  api/routes/print.js
  api/server.js
  package-lock.json
  package.json
  src/Pages/Profile/MemberView/InfoCard.js
  src/Pages/Profile/admin/AdminView.jsx
  test/LedSign.js
  util/setup-scripts/setup.bat
  util/setup-scripts/setup.sh
  util/testing-utils/tools.js
Labels: Refactoring

#353 2D Printing API Test
  api/routes/print.js
  package-lock.json
  test/2DPrinting.js
  test/frontend/2DPrinting.test.js
Labels: API, Testing

#352 Setup Copies Config File
  setup.py
Labels: enhancement

#355 Fix bcryptjs Functionality
  api/mailer/auth.js
  api/models/User.js
  api/routes/user.js
  src/Components/Navbar/UserNavbar.js
  src/Pages/3DPrinting/3DPrintForm.js
  src/Pages/LedSign/LedSign.js
Labels: API, bug

#308 Add ApiFunctions Class
  src/APIFunctions/2DPrinting.js
  src/APIFunctions/3DPrinting.js
  src/APIFunctions/ApiResponses.js
  src/APIFunctions/ErrorLog.js
  src/APIFunctions/Event.js
  src/APIFunctions/Image.js
  src/APIFunctions/LedSign.js
  src/APIFunctions/Profile.js
  src/APIFunctions/SignLog.js
  src/APIFunctions/User.js
  src/Pages/3DPrinting/3DPrintForm.js
  src/Pages/3DPrintingConsole/3DConsole.js
  src/Pages/EventManager/EventManager.js
  src/Pages/Events/EventList.js
  src/Pages/MembershipApplication/MembershipForm.js
  src/Pages/MembershipApplication/VerifyEmail.js
  src/Pages/Overview/Overview.js
  src/Pages/Profile/MemberView/PrintRequest.js
  test/frontend/EventList.test.js
  test/frontend/EventManager.test.js
Labels: API, Refactoring, enhancement

#342 Add macOS Testing to Travis
  .travis.yml
  setup.py
  util/setup-scripts/setup.bat
Labels: Testing, enhancement

#357 Downsize Dependency Count + Create util/ Directory
  api/constants.js
  api/models/User.js
  api/package-lock.json
  api/routes/3DPrintingForm.js
  api/routes/Event.js
  api/routes/mailChimp.js
  api/routes/officerManager.js
  api/routes/user.js
  api/server.js
  api/util/logger.js
  api/util/settings.js
  api/util/token-functions.js
  package-lock.json
  test/TokenFunctions.js
  test/mocks/TokenValidFunctions.js
  test/officerManager.js
Labels: Refactoring

#360 Add Google reCaptcha v2
  .travis.yml
  package-lock.json
  package.json
  src/Pages/MembershipApplication/GoogleRecaptcha.js
  src/Pages/MembershipApplication/MembershipForm.js
  src/config/config.example.js
Labels: Front End, enhancement

#361 Track Messages Written to SCE Sign
  api/index.js
  api/routes/LedSign.js
  api/routes/SignLog.js
  src/APIFunctions/LedSign.js
  src/APIFunctions/SignLog.js
  test/LedSign.js
  test/SignLog.js
Labels: API, enhancement

#372 Setup Copies src Config File
  setup.py
Labels: enhancement

#374 Add Testing for Windows on Travis
  .travis.yml
Labels: Testing, enhancement

#390 Refactor Admin Navbar Routing
  src/Routing.js
Labels: Refactoring, bug

#379 Save User's Emails as Lowercase
  api/routes/user.js
Labels: API, bug

#389 Prevent Server from Crashing due to no Token File
  .eslintrc.json
  api/mailer/mailer.js
  src/Pages/MembershipApplication/VerifyEmail.js
Labels: API, bug

#403 Allow Space for Async Arrow Function
  .eslintrc.json
  api/mailer/mailer.js
  api/routes/LedSign.js
  api/routes/print.js
  src/Pages/2DPrinting/2DPrinting.js
  src/Pages/3DPrintingConsole/3DConsole.js
  src/Pages/Profile/MemberView/PrintRequest.js
  test/frontend/EventList.test.js
  test/frontend/EventManager.test.js
  test/frontend/LedSign.test.js
Labels: enhancement

#402 Fix LedSign Unhandled Promise Rejection Warning
  api/routes/LedSign.js
Labels: API, bug

#363 Add Officer Schema
  api/constants.js
  api/models/OfficerManager.js
  api/routes/officerManager.js
  test/officerManager.js
Labels: API, enhancement
