Repository SCE-Development/Clark, pull requests merged in 2022-02, with the labels that each got.

#954 Merge multiple PRs into a single PR
  .github/workflows/combine-prs.yml
Labels: enhancement, metaverse

#977 Give Eslint warnings instead of errors when running website
  setup.py
Labels: enhancement

#980 Closes docker ports in production
  docker-compose.yml
Labels: bug, enhancement
