Repository SCE-Development/Clark, pull requests merged in 2022-04, with the labels that each got.

#1069 Adds dynamic URL to peripheral token verification
  api/util/token-verification.js
Labels: bug, API

#1071 Add dependency caching to pr builds
  .github/workflows/node.js.yml
Labels: enhancement, Refactoring, Testing

#1063 Remove unused dependencies in package.json
  api/package-lock.json
  api/package.json
  package-lock.json
  package.json
Labels: enhancement

#1080 Add new social medias to footer
  src/Components/Footer/Footer.js
  src/Components/Footer/Icons/DiscordIcon.js
  src/Components/Footer/Icons/FacebookIcon.js
  src/Components/Footer/Icons/InstagramIcon.js
  src/Components/Footer/Icons/LinkedinIcon.js
  src/Components/Footer/footer.css
Labels: enhancement, Front End

#1058 Remove Assumption about Prod Environment for Docker Build
  docker-compose.dev.yml
  nginx.dev.conf
  package-lock.json
Labels: enhancement

#1086 Remove unnecessary images
  docker-compose.dev.yml
  docker-compose.yml
Labels: bug, Refactoring

#1088 Fixed nginx issues
  nginx.conf
  nginx.dev.conf
Labels: bug

#1091 Fixed Discord login/connection
  api/config/config.example.json
  api/main_endpoints/routes/User.js
  api/main_endpoints/util/discord-connection.js
Labels: bug, API
